### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by y94anden** [Infinity95/open62541#4]
Description
===========
I have been testing your branch `feature/SecurityPolicy#Basic128Rsa15` and have found a few minor
issues that I thought I should share with you.

In file plugins/ua_securitypolicy_basic128rsa15.c
------------------------------------------------------------

* All mbedtls #includes use backslash instead of frontslash which fails compiling in linux.
* In function `policyContext_setCertificateTrustList_sp_basic128rsa15()`, certificate trust list is parsed using `mbedtls_x509_crt_parse_der()` (row 94). Is there a reason to require DER format, or could the function `mbedtls_x509_crt_parse()` be used instead?

In file plugins/ua_config_standard.c
--------------------------------------------------
In function `UA_ServerConfig_standard_basic128rsa15_new()`, the port is hardcoded to 16664 (row 333), but is available as an input parameter to the function, `portNumber`.

Application and product URI
---------------------------------------------------
I also have another issue that might require a slight rewrite. When using  `UA_ServerConfig_standard_basic128rsa15_new()`, the applicationURI and productURI are not set on the created endpoints. If I recall correctly, the UaExpert client requires that the URI in the application certificate matches that of the endpoint used. My workaround is currently as follows:

```cpp
UA_ServerConfig *config = UA_ServerConfig_standard_basic128rsa15_new(
    port,
    &cert,
    &privateKey,
    &trustList,
    NULL); // revocationList

config->applicationDescription.applicationUri = UA_STRING((char*)"<something that matches certificate URI>");
config->applicationDescription.productUri = UA_STRING((char*)"<something else>");

// Workaround
// Make sure that all endpoints also have the same applicationUri
for (unsigned int i = 0; i < config->endpoints.count; i++) {
    config->endpoints.endpoints[i].endpointDescription.server.applicationUri =
        config->applicationDescription.applicationUri;

    config->endpoints.endpoints[i].endpointDescription.server.productUri =
        config->applicationDescription.productUri;
}
```

Thank you for your effort! I am following your progress with great interest :)

**Comment by Infinity95** [comment]
First of all thank you for the input, i really appreciate that.

You're right, i believe the normal parse function could be used as well.
The hardcoded port was present on the plugin branch as well and i fixed it there. Seems i forgot to change it here as well, thanks for pointing that out.

The certificate loading and managmenet will require a rewrite anyways. I will probably be making a separate plugin for that (something like CertificateManager plugin), where the certificates are stored, managed and validated. From there the applicationUri and productUri could be extracted from the certificate and then stored in the endpoinnts that correspond to that certificate. I'll have to check what the standard says about that stuff.

I'm a bit busy right now and the plugin architecture has priority at the moment, so it might take some time to get to work on that.

**Comment by Infinity95** [comment]
All the issues should have been resolved, so i'm closing this.
The branch has been merged into the [master branch](https://github.com/open62541/open62541).
