### ISSUE TITLE
Decoding error when dealing with 5000 items per subscription

### ISSUE THREAD

**Issue by xiaoyanhao** [Infinity95/open62541#5]
Description
===========
I have been testing your branch `feature/SecurityPolicy#Basic128Rsa15_new` under the CTT test suite `Monitored Item Services/Monitor Items 5000` while using `Basic128Rsa15` security policy and `SignAndEncrypt` security mode and have gotten the following error:
```
CreateMonitoredItems.Response.ResponseHeader.ServiceResult is Bad: BadDecodingError (0x80070000)
```
However, all tests pass when using `None` security policy and `None` security mode.

**Comment by Infinity95** [comment]
I'm currently short on time, but will check it out if i have time. If you find the cause in the meantime, feel free to make a pull request.

**Comment by Infinity95** [comment]
The branch was merged into the open62541 master branch and i think i might have found what caused the issue. I couldn't test it yet. Maybe you could check with the [master branch ](https://github.com/open62541/open62541) and see if the issue is resolved?
